version: '3.4'
services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
      - 8000
    ports:
      - "8080:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
