version: '3.0'

services:
  flask_backend:
    container_name: flask_backend
    restart: always
    ports:
      - "8000:8000"
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind "0.0.0.0:8000" wsgi:app
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_backend